# This is a basic workflow to help you get started with Actions

name: ci-test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  DEV_IMAGE_NAME: aicc/develop/aicc-frontend
  IMAGE_NAME: aicc/aicc-frontend
  VERSION: 1.1.9

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "도커 이미지 레지스터리 위치 결정"
        if: github.ref_name != 'main'
        run: echo "DEPLOY_IMAGE_NAME=${{ env.DEV_IMAGE_NAME }}" >> $GITHUB_ENV

      - name: "도커 이미지 레지스터리 위치 결정"
        if: github.ref_name == 'main'
        run: echo "DEPLOY_IMAGE_NAME=${{ env.IMAGE_NAME }}" >> $GITHUB_ENV
        
      - name: Runs setting TAG
        run: |
          echo "TAG=${{ env.VERSION }}-$(date -d '9 hour' +'%Y%m%d')-${{ github.run_number }}" >> $GITHUB_ENV
          echo "GITHUB_ENV.TAG = $GITHUB_ENV.TAG"
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          echo "DEPLOY_IMAGE_NAME = ${{ env.DEPLOY_IMAGE_NAME }}"
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: develop

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world! test ${{github.base_ref}}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "test dev - ${{ github.base_ref }}"
          echo "github.repository = ${{ github.repository }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
          echo "github.sha = ${{ github.sha }}"
          echo "github.event_name = ${{ github.event_name }}"
          echo "github.actor = ${{ github.actor }}"
          echo "github.run_id = ${{ github.run_id }}"
          echo "github.run_number = ${{ github.run_number }}"
          echo "github.workflow = ${{ github.workflow }}"
          echo "github.action = ${{ github.action }}"
          echo "github.event_path = ${{ github.event_path }}"
          echo "github.base_ref = ${{ github.base_ref }}"
          echo "github.head_ref = ${{ github.head_ref }}"
          echo "GITHUB_ENV = $GITHUB_ENV"
          echo "env.TAG = ${{ env.TAG }}"
          

